config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root "home#index"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get '/users/dash_boards', to: 'dash_boards#index'
  namespace :users do
    resources :articles
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { maximum: 10 }
  validates :content, presence: true
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :name, presence: true

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ログイン済ユーザーのみにアクセスを許可する
  before_action :authenticate_user!
  # deviseコントローラーにストロングパラメータを追加する
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/dash_boards_controller.rb
class DashBoardsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/articles_controller.rb
# app/controllers/users/articles_controller.rb
class Users::ArticlesController < ApplicationController
  def index
    # 一覧表示のための処理
    @articles = Article.all
  end

  def show
    # 詳細表示のための処理
    @article = Article.find(params[:id])
  end

  def new
    # 新規作成画面の表示
    @article = Article.new
  end

  def create
    # 新規作成処理
    @article = Article.new(article_params)
    if @article.save
      redirect_to users_articles_path, notice: "記事を作成しました"
    else
      render :new
    end
  end

  def edit
    # 編集画面の表示
    @article = Article.find(params[:id])
  end

  def update
    # 更新処理
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to users_article_path(@article), notice: "記事を更新しました"
    else
      render :edit
    end
  end

  def destroy
    # 削除処理
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to users_articles_path, notice: "記事を削除しました"
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :image)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController #deviseの該当クラスを継承させる

  def create
    super do                                             # 他はdeviseの機能をそのまま流用する
      resource.update(confirmed_at: Time .now.utc)       # Welcomeメールを送信した上で、skip_confirmation!と同一処理を行い自動で認証クローズさせる
    end
  end

  def update_resource(resource, params)
    if params[:password].present? || params[:password_confirmation].present?
      super
    else
      params.except!(:current_password)
      resource.update_without_password(params)
    end
  end


  def after_update_path_for(_resource)
    users_dash_boards_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dash_boards_helper.rb
module DashBoardsHelper
end

app/helpers/users/articles_helper.rb
module Users::ArticlesHelper
end

app/views/dash_boards/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6 text-center">
      <h1>Dash Boards</h1>
      <h2><%= current_user.name %></h2>
      <a href="<%= edit_user_registration_path %>" class="btn btn-primary"><%= t('devise.dash_boards.edit')%> </a><br>
      <%= link_to t('devise.dash_boards.logout'), destroy_user_session_path, method: :delete, class: "btn btn-warning" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#inde111x</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeforeIntern</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </head>


  <body>
      <div class="container">
        <%= yield %>
      </div>
  </body>

</html>

app/views/users/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/articles/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="text-center">記事の編集</h1>
      
      <%= form_with(model: @article, url: users_article_path(@article), method: :patch) do |form| %>
        <div class="form-group">
          <%= form.label :タイトル %>
          <%= form.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :内容 %>
          <%= form.text_area :content, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :画像 %><br>
          <%= form.file_field :image, class: "form-control-file" %>
        </div>
        <div class="text-center mt-3">
          <%= form.submit "更新する", class: "btn btn-primary" %>
        </div>
      <% end %>

      <div class="text-left mt-3">
        <%= link_to "戻る", users_article_path(@article), class: "btn btn-secondary" %>
      </div>

    </div>
  </div>
</div>

app/views/users/articles/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="text-center">記事一覧</h1>
      
      <div class="text-center">
        <%= link_to t('devise.article.index.new_users_article'), new_users_article_path, class: "btn btn-primary btn-block", style: "width: 500px;" %>
      </div>

      <table class="table">
        <thead>
          <tr>
            <th>詳細</th>
            <th>タイトル</th>
            <th>内容</th>
            <th>画像</th>
            <th>編集 ・ 削除</th> <!-- 編集と削除を一行にまとめる -->
          </tr>
        </thead>
        <tbody>
          <% @articles.each do |article| %>
            <tr>
              <td><%= link_to "詳細", users_article_path(article), class: "btn btn-primary btn-block" %>
              <td><%= article.title %></td>
              <td><%= article.content %></td>
              <td>
                <% if article.image.present? && article.image.attached? %>
                  <%= image_tag url_for(article.image), size: "100x100" %>
                <% else %>
                  画像なし
                <% end %>
              </td>
              <!-- 編集と削除を一行にまとめる -->
              <td>
                <div class="d-inline-block">
                  <%= link_to "編集", edit_users_article_path(article), class: "btn btn-success btn-sm mr-2" %>
                </div>
                <div class="d-inline-block">
                  <%= button_to "削除", users_article_path(article), method: :delete, data: { confirm: "この記事を削除してもよろしいですか？" }, class: "btn btn-danger btn-sm", style: "white-space: nowrap;" %>
                </div>
              </td>
              <td>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/users/articles/new.html.erb
<%= form_with(model: @article, url: users_articles_path, method: :post) do |form| %>
  <h1 class="text-center">記事の新規作成</h1>

  <% if @article.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, t('devise.article.new.title') %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content, t('devise.article.new.content') %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image, t('devise.article.new.image') %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="text-center">
    <%= form.submit t('devise.article.new.create'), class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to t('devise.article.new.back'), users_articles_path %>

app/views/users/articles/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="text-center">記事詳細</h1>
      
      <table class="table">
        <thead>
          <tr>
            <th>タイトル</th>
            <th>内容</th>
            <th>画像</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @article.title %></td>
            <td><%= @article.content %></td>
            <td>
              <% if @article.image.present? && @article.image.attached? %>
                <%= image_tag url_for(@article.image), size: "100x100" %>
              <% else %>
                画像なし
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>

      <div class="text-center mb-3">
        <div class="d-inline-block mr-2">
          <%= link_to "編集", edit_users_article_path(@article), class: "btn btn-success btn-sm mr-2" %>
        </div>
        <div class="d-inline-block">
          <%= button_to "削除", users_article_path(@article), method: :delete, data: { confirm: "この記事を削除してもよろしいですか？" }, class: "btn btn-danger btn-sm", style: "white-space: nowrap;" %>
        </div>

      </div>

      <div class="text-center mt-3">
        <%= link_to "記事一覧に戻る", users_articles_path, class: "btn btn-primary" %>
      </div>

    </div>
  </div>
</div>